### ISSUE TITLE
pls check test_remove_empty_list_raise_error

### ISSUE THREAD

**Issue by wenima** [wenima/data-structures#11]
```
def test_remove_empty_list_raise_error(create_empty_dbl_ll):
    """Test remove on empty list raises an Index Error."""
    dll = create_empty_dbl_ll
    with pytest.raises(IndexError):
        dll.remove("something")
```

doesn't raise an IndexError as it's actually not trying to remove anything as the search fails to look up the node object for this input

**Comment by CCallahanIV** [comment]
I think we're supposed to raise an IndexError in this case.  We can discuss tomorrow.

**Comment by wenima** [comment]
that's not what we do for linked lists

**Comment by CCallahanIV** [comment]
Test is corrected - now raises a ValueError!
