### ISSUE TITLE
DLL: Append should mirror push

### ISSUE THREAD

**Issue by CCallahanIV** [wenima/data-structures#37]
Same comments as for push, but for append.

Append should mirror push.

**Comment by wenima** [comment]
yeah good point, so I think I wrote push first and then later when I wrote append, I was tyrying to make it a little nicer and used the nodes collection we had. 

So the proposal is to keep append and change push to look like append and minimize the complexity with checking for length and all. Yes, I would be in favor of this, good catch!

**Comment by wenima** [comment]
after discussion we agreed that use of generator/list comprehension here is not good as it's O(n) as Ted pointed out.

**Comment by CCallahanIV** [comment]
Rewrote, mirrors push(), O(1) assignments.
