### ISSUE TITLE
on branch queue in test_queue - identify duplicates and remove

### ISSUE THREAD

**Issue by wenima** [wenima/data-structures#48]
for example:

```python
def test_create_queue_with_iter_correct_prev_nxt(new_q):
    """Creating a queue with an iter head.nxt and tail.prev are correct."""
    assert new_q._container.head.nxt.value == TEST_ITER[1]
    assert new_q._container.tail.prev.value == TEST_ITER[-2]
```

since we use composition and call the init method and have tested that tail and head is set correctly, we don't need to check nxt prev etc as these are byproducts of push in DblLinkedList working correctly.

**Comment by CCallahanIV** [comment]
That's a reasonable assumption - we know the DLL has been tested in that way.  No need to test the Queue in that way.
